services:
  db:
    container_name: url_shortener_db
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_net

  api1:
    container_name: url_shortener_api_1
    build: ./Api/url-shortener
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_net

  api2:
    container_name: url_shortener_api_2
    build: ./Api/url-shortener
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - backend_net

  api3:
    container_name: url_shortener_api_3
    build: ./Api/url-shortener
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - backend_net

  api4:
    container_name: url_shortener_api_4
    build: ./Api/url-shortener
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - backend_net

  api5:
    container_name: url_shortener_api_5
    build: ./Api/url-shortener
    ports:
      - "8084:8080"
    depends_on:
      - db
    networks:
      - backend_net

  nginx:
    container_name: nginx_load_balancer
    build: ./Nginx
    ports:
      - "2007:2007"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  postgres_data: