services:
  db:
    container_name: url_shortener_db
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  api:
    container_name: url_shortener_api
    build: ./Api/url-shortener
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  postgres_data: