spring:
  application:
    name: url-shortener

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:url_shortener_db

